### ISSUE TITLE
Duplicate ports

### ISSUE THREAD

**Issue by diegosc78** [fydrah/helm-charts#2]
https://github.com/fydrah/helm-charts/blob/master/transmission/templates/service.yaml seems to have duplicate TCP ports (lines 38 and 42).

Furthermore, if you configure LoadBalancer, there are problems with having same peer port on same services (tcp and udp). According to another blogs it can be solved by defining 2 services (one for TCP port and other for UDP) and having some annotations. See attached modified template i've used
[service.txt](https://github.com/fydrah/helm-charts/files/5504591/service.txt)

Obviously i've also added to values that annotations... for metallb... "metallb.universe.tf/allow-shared-ip: transmission-svc"

**Comment by fydrah** [comment]
Hi @diegosc78 ,

Good catch, I'm fixing it. And I will add annotations for svc into value.yaml too.

**Comment by fydrah** [comment]
Fix available in 2.1.0 release: https://github.com/fydrah/helm-charts/releases/tag/transmission-2.1.0
